### ISSUE TITLE
date control up/down

### ISSUE THREAD

**Issue by jasperfu** [MattyAyOh/Mortality#115]
up/down arrow buttons don't consistently work

**Comment by MattyAyOh** [comment]
could you reproduce this again?  i forgot how you did it

**Comment by jasperfu** [comment]
https://i.imgur.com/AlXMKqC.png 
if you click the arrows enough it starts highlighting the wrong arrow and stops working

**Comment by MattyAyOh** [comment]
Ah yes I see it on Windows, but not Mac

Unfortunately we are using the HTML5 `input` element, with type `date`

As the control is part of the framework, and not a custom control, we don't have the ability to fix this issue

Marking this issue closed
