### ISSUE TITLE
Setting for more precision in decimal view

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/Mortality#121]
Currently I only show 3 figures after the decimal

- If the smallest precision is set to "Use Decimal", show a checkbox called "Extended decimal precision" (or something like that?)
- If the checkbox is checked, make it show 10 figures instead of 3

**Comment by MattyAyOh** [comment]
This one should be pretty straight forward, @jasperfu

**Comment by jasperfu** [comment]
@MattyAyOh what does the zeroFill function do that toFixed doesn't?

**Comment by MattyAyOh** [comment]
`toFixed` sets numbers after decimal point

`zeroFill` pads the front with zeroes to force a string with `width` digits

so `(10,3)` -> `"010"`

**Comment by MattyAyOh** [comment]
yeah I should've probably named it `padZeros` or something

**Comment by MattyAyOh** [comment]
shooting to release Thursday night (1/4), btw

**Comment by jasperfu** [comment]
I staged/committed through sourcetree I think but I don't see the commit in github? also my sourcetree seems to be like 5 days behind
https://i.imgur.com/JSRqplU.png

**Comment by MattyAyOh** [comment]
So SourceTree and Github are both clients for Git, a source control system

SourceTree allows you to visualize a Git repository (it's commits, branches, tags, graph, and files at the commits)
GitHub also allows you to visualize a Git repository almost the same way (the [graph ](https://github.com/MattyAyOh/Mortality/network) has much less information)
But it does allow you to view all of the files on a branch of the repo, as well as a bunch of other insights.
GitHub also has issues, pull requests, commenting, that can all reference Git commits
But most importantly, GitHub also hosts repositories.

On your computer right now, you have a Git repository for Mortality, we call this the local repository
GitHub hosts the same copy of the repository, called remote (though you can have multiple remotes, so each remote is named,  the default name for a remote repository is `origin`), because it's hosted "in the cloud"

Whenever you add a commit to a Git Repository, nobody else is going to see it, unless they are looking at your local repository

After you Commit, you need to also Push your commits into the Remote repository, so that people can see the commits.

"Your sourcetree is 5 days behind" is incorrect in a few ways:
- SourceTree itself cannot be behind, it is a client.  Only your local repository can be behind, and more specifically, it is your local repository's snapshot of the current branch that is behind.  If you look at SourceTree's graph of your repository, you can look at where you local branch is at (e.g, `master`), and you can see where remote's branch is at (`origin/master`)  
If you were on the `master` branch in your local repository, and I pushed a couple commits to the `origin/master`, SourceTree would tell you that your `master` is 2 commits behind, and that you need to Pull the latest changes
- With that being said, there is no such concept as "days behind" in Git, it's just commits behind
- In the screenshot you provided, it looks like your local master is up-to-date with the remote repository, but as you can see you branched off of `master`, and made a commit in that new branch.  Note how there is no `origin` in front of your branch name.  This means that only your local repository has this branch.  You need to `push` your branch into `origin`, which will happen automatically after you push your commit to origin
- Kind of related lesson, but "fetch" is something that SourceTree will automatically periodically do for you, but it is just having your local repository check up with remote to see where all of the branches are at.  It is possible that you open SourceTree, and it says your `master` is up-to-date with `origin/master`, but when you Fetch from the remote repo, all of the sudden it knows that your `master` is like 10 commits behind `origin/master`.  Fetching does not change any files in your repository.  Pull will first do a `git fetch`, to make sure there are commits that you are missing, and then it will pull down those commits into your local repository

**Comment by MattyAyOh** [comment]
Also to clarify the commit process:

1) First you make sure you are on the correct commit you want to make changes on (typically latest `master`, for us)
2) Branch off of that commit
3) Make your changes
4) Stage the exact files/lines of code that you want in your commit
5) Create a commit containing the changes
6) Push the changes into the remote repository

**Comment by MattyAyOh** [comment]
Oh also, only show the checkbox if "decimal" is selected as smallest precision

**Comment by MattyAyOh** [comment]
This is the last issue left, waiting on youuuu~

**Comment by jasperfu** [comment]
oh sorry will finish didn't realize it was thursday

**Comment by MattyAyOh** [comment]
When the smallest precision is not decimal,
And you load the settings for the first time, the checkbox still shows

need to default the checkbox to be hidden, and on load, show it if the smallest precision is decimal

**Comment by MattyAyOh** [comment]
Also, it looks like you rebased correctly, but you merged the wrong branch again

You merged Master into your branch, instead of your branch into master
