### ISSUE TITLE
Date is incorrect

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/Mortality#19]
Dear Ao, This app is definitely here to stay as my homepage, and I especially love the countdown feature of the latest update! However, after this update, the circle charts, which to my understanding represents a month of life per circle, becomes inaccurate. On my life counter (not countdown), I am on exactly the 6th month of my age since my birth day. However, the current circle is shown to be a fraction, instead of being fully filled as a complete month. I patiently await your favourable response. Thank you for developing my favourite extension!
Reply
Application version: 4.1.0
Client version: 5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Reported date: 11/19/16 6:56 AM
Reported by: A Google User
Developer's Notes: Add a note

**User's birthdate: 15/05/2000**

**Comment by hantuzun** [comment]
The reason is that the length of the first year varies with the birthday

**Comment by MattyAyOh** [comment]
Hi Han, 
Thanks for stopping by  ^^
What do you mean length of the first year?  Do you mean factoring in leap days?

**Comment by hantuzun** [comment]
Thanks Matt.

The number of months in the first year of lifespan is not just 12. It varies with the birthday.

**Comment by MattyAyOh** [comment]
Fixed by 4edb11b
