### ISSUE TITLE
Quality of circles?

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/Mortality#24]
> Would it be possibly to add a higher quality to the time and background circles. Looks a bit blurry/ pixelated - would be perfect with higher quality and sharp text! :)

**Comment by kotulakk** [comment]
i didn't look at how you currently do it, but it should be possibly by using svg's instead of the div/css you have now.

**Comment by MattyAyOh** [comment]
This was a user submitted report, it has to be investigated, I agree with you I don't see what they were talking about, doesn't look blurry to me.  I'm not sure how they were able to get into a state where it's blurry-- maybe huge monitor?  ionno

**Comment by MattyAyOh** [comment]
Confirmed that this is somehow user error.  SVGs are being used, so nothing we can do

**Comment by MattyAyOh** [comment]
Had to double-check on windows.  Confirmed
