### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by hantuzun** [MattyAyOh/Mortality#30]
Add a license please

**Comment by MattyAyOh** [comment]
Does a project need a license if it doesn't ask for money?

**Comment by hantuzun** [comment]
Hi @MattyAyOh,

Unless you provide a specific license you own all the rights of the project. Therefore, your project would be open source but not free. Because you may sue anyone using your code without your explicit permission.

Writing a license clarifies who can use your project and its code in which manner. To make it easy for you to write licenses and for your users to understand them it's common to use a known license. You name it, GPL, Apache, MIT Licenses...

If you want to add a license you can have a look at [Choose a license](http://choosealicense.com/) website by GitHub.

Trivia: There had been even a bot opening issues on projects like I did once upon a time: 
https://www.producthunt.com/tech/add-a-license-please :)

**Comment by MattyAyOh** [comment]
Got it, thanks for the info :)

**Comment by hantuzun** [comment]
Thanks Matt
