### ISSUE TITLE
The expected lifespan should be varied

### ISSUE THREAD

**Issue by hantuzun** [MattyAyOh/Mortality#31]
The lifespan should be the sum of the lengths of life chapters. Each square should continue representing a month.

**Comment by MattyAyOh** [comment]
Is this kind of related to #13 ?

Give the users the ability to choose the number of circles/squares in the background, as well as the unit each circle/square represents? (in this case, month)

**Comment by hantuzun** [comment]
Yes Matt, you may close this one.

**Comment by MattyAyOh** [comment]
👍
