### ISSUE TITLE
Consistent collection of icons for sidepanel

### ISSUE THREAD

**Issue by kotulakk** [MattyAyOh/Mortality#34]
design new sp icons that have matching style.

**Comment by MattyAyOh** [comment]
What are sp icons?

**Comment by MattyAyOh** [comment]
https://creativemarket.com

user: mattyayoh
pass: mayomayo123

top-right, hover over the username, click on "Purchases"

you can see the icons, fonts, misc assets there

**Comment by MattyAyOh** [comment]
Bought and currently using these icons: https://creativemarket.com/XusBadia/667495-Zeus-626-Icons-Set
