### ISSUE TITLE
Show countdown in seconds only

### ISSUE THREAD

**Issue by c4po** [MattyAyOh/Mortality#99]
can you add an option to show the countdown in seconds only?
eg. instead showing 10 years 1 months 10 days 1 hours 10 minutes 1 seconds, just show xxxxxxxxxxxxx seconds

**Comment by MattyAyOh** [comment]
This shouldn't be too bad to implement, might slate it for the next release, if not then the next one :)

**Comment by MattyAyOh** [comment]
Released in 5.1.0
